theme = "stylix"
[editor]
cursorline = true
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "."
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"

[keys.normal]
ins = "insert_mode"
